[build.environment]
  NODE_VERSION = "14"

[build]
  publish = "dist"
  command = "npx ts-node script.ts"

[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200

[[edge_functions]]
  path = "/*"
  function = "auth"
