[build.environment]
  NODE_VERSION = "14"

[build]
  publish = "dist"
  command = "npx ts-node script.ts react"

[[redirects]]
  from = "/elasticsearch/*"
  to = "/elasticsearch/index.html"
  status = 200

[[redirects]]
  from = "/react/*"
  to = "/react/index.html"
  status = 200

[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200

[[edge_functions]]
  path = "/*"
  function = "auth"
