// Builds everything that gets deployed, into a single folder: build/
//
//   node scripts/build-all.mjs              # everything
//   node scripts/build-all.mjs --only site  # or --only slides
//   node scripts/build-all.mjs --no-pdf     # skip the (slow) PDF export
//   node scripts/build-all.mjs --install    # force a dependency install first
//
// Exporting the decks to PDF drives a real browser. On CI it is downloaded with
// `playwright install chromium`; locally, point SLIDEV_CHROME at a Chrome you
// already have to skip that download:
//
//   SLIDEV_CHROME=~/.cache/ms-playwright/chromium-*/chrome-linux64/chrome \
//     node scripts/build-all.mjs
//
// Layout produced:
//
//   build/
//     index.html            the workshops site (Starlight)
//     javascript/           its workshop pages
//     vuejs-advanced/
//     _pagefind/            its search index
//     slides/
//       javascript/         the Slidev deck
//       vuejs-advanced/
//     downloads/
//       javascript-slides.pdf
//       javascript-solutions.zip
//     _redirects            SPA fallback, one rule per deck
//
// The site lives at the root and the decks under /slides/<training>/, so the
// landing page of the domain is the workshops index.

import { spawnSync } from 'node:child_process';
import { createWriteStream, existsSync } from 'node:fs';
import { cp, mkdir, rm, writeFile, readdir, stat } from 'node:fs/promises';
import archiver from 'archiver';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { TRAININGS } from './trainings.mjs';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(repoRoot, 'build');
const siteDir = join(repoRoot, 'site');
const trainingDir = join(repoRoot, 'training');

const args = process.argv.slice(2);
const only = args.includes('--only') ? args[args.indexOf('--only') + 1] : null;
const forceInstall = args.includes('--install');
const withPdf = !args.includes('--no-pdf');
// Netlify (and any CI) starts from a bare checkout: the sub-projects have to be
// installed by us, because the host only installs the root package.json.
const onCI = process.env.CI === 'true' || process.env.NETLIFY === 'true';

const buildSite = only === null || only === 'site';
const buildSlides = only === null || only === 'slides';
const localChrome = process.env.SLIDEV_CHROME;

function run(command, commandArgs, cwd, { allowFailure = false } = {}) {
  console.log(`\n$ ${command} ${commandArgs.join(' ')}   (in ${cwd.replace(repoRoot, '.')})`);
  const result = spawnSync(command, commandArgs, { cwd, stdio: 'inherit', shell: false });
  if (result.status === 0) {
    return true;
  }
  if (allowFailure) {
    console.warn(`\n⚠ non-fatal: ${command} ${commandArgs.join(' ')}`);
    return false;
  }
  console.error(`\n✖ failed: ${command} ${commandArgs.join(' ')}`);
  process.exit(result.status ?? 1);
}

function install(cwd, command, commandArgs) {
  if (!forceInstall && !onCI && existsSync(join(cwd, 'node_modules'))) {
    return;
  }
  run(command, commandArgs, cwd);
}

/** Zips a folder, skipping everything that is regenerated by an install/build. */
function zip(sourceDir, destFile, prefix) {
  return new Promise((resolve, reject) => {
    const output = createWriteStream(destFile);
    const archive = archiver('zip', { zlib: { level: 9 } });
    output.on('close', () => resolve(archive.pointer()));
    archive.on('warning', (error) => console.warn(`⚠ ${error.message}`));
    archive.on('error', reject);
    archive.pipe(output);
    archive.glob('**/*', {
      cwd: sourceDir,
      dot: true,
      ignore: [
        '**/node_modules/**',
        '**/dist/**',
        '**/.astro/**',
        '**/coverage/**',
        '**/*.log',
      ],
    }, { prefix });
    archive.finalize();
  });
}

async function directorySize(dir) {
  let total = 0;
  for (const entry of await readdir(dir, { withFileTypes: true, recursive: true })) {
    if (entry.isFile()) {
      total += (await stat(join(entry.parentPath, entry.name))).size;
    }
  }
  return `${(total / 1024 / 1024).toFixed(1)} MB`;
}

console.log(`Building ${TRAININGS.map((t) => t.label).join(' + ')} into build/`);

await rm(outDir, { recursive: true, force: true });
await mkdir(outDir, { recursive: true });

// --- 1. The decks (Slidev) --------------------------------------------------
// One build per deck. `--base` matters: without it the deck requests its assets
// from the domain root and every chunk 404s once it is served from a sub-path.
if (buildSlides) {
  // training/ is a pnpm project; the CI host only knows about the root, so pnpm
  // is fetched on demand rather than assumed to be installed.
  install(trainingDir, 'npx', ['--yes', 'pnpm@10', 'install', '--frozen-lockfile']);

  // The PDF export needs a browser. SLIDEV_CHROME skips the download when one is
  // already on the machine — which is the normal case locally, and never on CI.
  if (withPdf && !localChrome) {
    run('npx', ['--yes', 'pnpm@10', 'exec', 'playwright', 'install', 'chromium'], trainingDir);
  }

  for (const training of TRAININGS) {
    if (!existsSync(join(trainingDir, training.deck))) {
      console.warn(`⚠ ${training.deck} not found — deck skipped`);
      continue;
    }
    const deckOut = join(outDir, 'slides', training.slug);

    // The deck itself: fast, and never allowed to fail.
    run(
      'npx',
      [
        '--yes',
        'pnpm@10',
        'exec',
        'slidev',
        'build',
        training.deck,
        '--base',
        `/slides/${training.slug}/`,
        // `--out`, not `--output`: the latter belongs to the export (PDF/PNG)
        // options and is silently ignored here, leaving the deck in training/dist.
        '--out',
        deckOut,
      ],
      trainingDir,
    );

    // The PDF: a separate, slow step that drives a real browser over every
    // slide. A deck that fails to export must NOT take the deploy down with it —
    // the Resources page simply drops its PDF link (see sync-workshops.mjs).
    if (withPdf) {
      run(
        'npx',
        [
          '--yes',
          'pnpm@10',
          'exec',
          'slidev',
          'export',
          training.deck,
          '--output',
          join(deckOut, 'slidev-exported.pdf'),
          // The defaults are tuned for a small deck. A 200-slide deck never
          // reaches `networkidle`, and not even `load` — the cover slide pulls a
          // background from source.unsplash.com, which no longer answers.
          // `domcontentloaded` does not wait for that image.
          '--wait-until',
          'domcontentloaded',
          '--timeout',
          '300000',
          // Rendering 200 slides in one print page is what blows the budget;
          // per-slide navigation is slower per slide but finishes.
          '--per-slide',
          ...(localChrome ? ['--executable-path', localChrome] : []),
        ],
        trainingDir,
        { allowFailure: true },
      );
    }
  }
}

// --- 2. Downloads -----------------------------------------------------------
// What the Resources page of each training links to: the deck as a PDF, and the
// worked answers as a zip.
const downloadsDir = join(outDir, 'downloads');
await mkdir(downloadsDir, { recursive: true });

for (const training of TRAININGS) {
  // The PDF is produced inside the deck by `--download`; copy it out under a
  // name that says what it is, and leave the original where the deck's own
  // download button expects it.
  const exported = join(outDir, 'slides', training.slug, 'slidev-exported.pdf');
  if (existsSync(exported)) {
    await cp(exported, join(downloadsDir, `${training.slug}-slides.pdf`));
  } else if (buildSlides && withPdf) {
    console.warn(`⚠ no PDF produced for ${training.label}`);
  }

  const solutionsDir = join(repoRoot, training.solutions ?? '');
  if (training.solutions && existsSync(solutionsDir)) {
    const bytes = await zip(
      solutionsDir,
      join(downloadsDir, `${training.slug}-solutions.zip`),
      `${training.slug}-solutions`,
    );
    console.log(`  ${training.slug}-solutions.zip  ${(bytes / 1024 / 1024).toFixed(1)} MB`);
  }
}

// --- 3. The workshops site (Starlight) -------------------------------------
// Built LAST, and copied to the root of build/: its Resources pages look at
// build/downloads/ to decide which links they can honestly offer.
// It goes to the root of build/, so that the domain lands on the workshop index.
// `npm run build` runs the README ➜ Starlight sync first (prebuild).
if (buildSite) {
  install(siteDir, 'npm', ['ci']);
  run('npm', ['run', 'build'], siteDir);
  await cp(join(siteDir, 'dist'), outDir, { recursive: true });
}

// --- 4. SPA fallback --------------------------------------------------------
// A Slidev deck is a single-page app with history routing: /slides/x/12 is a
// client-side route, not a file. Without this, a reload on slide 12 is a 404.
// The rules are not forced, so real files (assets, chunks) still win.
const redirects = TRAININGS.map(
  (training) =>
    `/slides/${training.slug}/*  /slides/${training.slug}/index.html  200`,
).join('\n');
await writeFile(join(outDir, '_redirects'), `${redirects}\n`);

console.log('\n─────────────────────────────────────────');
console.log(`build/            ${await directorySize(outDir)}`);
console.log('  /               the workshops site');
const pad = Math.max(...TRAININGS.map((t) => t.slug.length));
for (const training of TRAININGS) {
  console.log(`  /slides/${training.slug}/`.padEnd(pad + 12) + `${training.label} deck`);
}
console.log('─────────────────────────────────────────');
console.log('\nPreview it exactly as Netlify will serve it:');
console.log('  npx serve build          (or: npx netlify dev)');
