== Internationalisation

=== Internationalisation

* Dans une application, nous devons
** formatter les dates, nombres, ...
** internationaliser les messages

=== Intl

* API native disponible dans les navigateur
* Propose plusieurs constructeurs
** `DateTimeFormat`
** `NumberFormat`
** `RelativeTimeFormat`

=== Intl

[source, javascript]
----
const date = new Date(Date.UTC(2012, 11, 20, 3, 0, 0));

console.log(new Intl.DateTimeFormat('en-US').format(date));
//12/20/2012
----

=== Intl

[source, javascript]
----
const number = 123456.789;

console.log(new Intl.NumberFormat('de-DE', {
        style: 'currency',
        currency: 'EUR'
    }).format(number)
);
// 123.456,79 €
----

=== Intl

[source, javascript]
----
const rtf = new Intl.RelativeTimeFormat('en', {
    style: 'narrow'
});

console.log(rtf.format(-1, 'day'));

//"1 day ago"
----

=== Manipulation des dates

* Plusieurs librairies sont disponibles :
** moment
** date-fns
** dayjs

=== react-i18next

* Il faut à présent internationaliser les messages
* *react-i18next* est une librairie permettant :
** de définir des dictionnaires
** définir la langue par défaut
** changer de langue au runtime
** utiliser des plugins

=== react-i18next

* Première chose à faire : configurer !

[source, javascript]
----
import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const resources = {
  en: {
      translation: {
          WELCOME: "Welcome"
      },
  },
  fr: {
      translation: {
          WELCOME: "Bienvenue"
      },
  },
};
...
----

=== react-i18next

[source, javascript]
----
...

i18n
  .use(initReactI18next)
  .init({
    resources,
    lng: "en",
  });

export default i18n;
----

=== react-i18next

* Une fois configurée, nous pouvons l'importer dans notre application

[source, javascript]
----
import "./i18n";
----

=== react-i18next

* Pour intéragir avec le dictionnaire, plusieurs solutions.
** via un hook

[source, javascript]
----
import { useTranslation } from 'react-i18next';

function App () {
  const { t } = useTranslation()
  return <h1>{t('Welcome to React')}</h1>
}

export default App;
----

=== react-i18next

* avec un HoC

[source, javascript]
----
import { withTranslation } from 'react-i18next';

function App ({ t }) {
  return <h1>{t('Welcome to React')}</h1>
}

export default withTranslation()(App);
----

=== react-i18next

* Les méthodes définies précédemment nous permettent également de manipuler un objet `i18n`.

[source, javascript]
----
const LanguageSwitcher = () => {
    const {  i18n } = useTranslation();
    return (
        <>
            <button onClick={() => i18n.changeLanguage("fr")}>FR</button>
            <button onClick={() => i18n.changeLanguage("en")}>EN</button>
        </>
    );
}
export default LanguageSwitcher;
----

=== react-i18next - ICU

* La syntaxe ICU est une suntaxe standardisée.
* Permet de pluraliser des messages
* Utilisable dans `react-i18next` via l'utilisation de `i18next-icu`

[source, javascript]
----
import ICU from "i18next-icu";

i18n
    .use(initReactI18next)
    .use(new ICU({}))
----

=== react-i18next - ICU

[source, javascript]
----
{
  nbFriend:
        "{count, plural, =0 {aucun ami} =1 {un ami} other {# amis}}",
}
----

[source, javascript]
----
{t("nbFriend", { count: 3 })}
----
