== TypeScript

=== TypeScript

* Typescript est un superset de JavaScript
* Développé par Microsoft et utilisé dans de nombreux projets
* Ajoute notamment le typage au langage JavaScript
* Nécessite une phase de compilation
* Les fichiers utilisent l'extension `.ts`

=== Utiliser TypeScript avec React

[source]
----
create-react-app demo --template typescript
----

=== Types

* Nous pouvons :
** typer les paramètres des fonctions
** typer les valeurs retournées des fonctions
** typer les variables d'une instance d'un objet
** créer des interface
** définir des génériques

=== Types

[source, typescript]
----
function lowercase(word: string): string {
    return word.toLowerCase();
}
----

=== Types

* Si nous utilisons la méthode avec la mauvaise signature, nous allons avoir des erreurs de compilation.

[source, typescript]
----
lowercase("react") // OK
lowercase(1) // TypeScript Error
lowercase("react").length // OK
lowercase("react").push({ }) // TypeScript Error
----

=== Custom Types

* Nous pouvons définir des types custom via :
** des classes
** des interfaces
** via le mot clé `type`

[source]
----
type User = {
    firstName: string;
    lastName: string;
    age ?: number
}
const user: User = { firstName: 'James`, lastName: 'Bond' };
----

=== Typer les props

* Nous allons utiliser le même mot clé afin de typer les `props` d'un composant.

[source, typescript]
----
import { FC } from "react"

type UserCardProps = {
    user: User;
}
const UserCard: FC<UserCardProps> = ({ user }) => {

}
----
